### ISSUE TITLE
Move event listener logic into dedicated service

### ISSUE THREAD

**Issue by Guite** [goetas/MultipartUploadBundle#14]
Hello,

it would be great if `MultipartRequestListener` would only react on the event but call an external (separate) class, e.g. `RequestProcessor` or similar, for doing the actual work.

Benefit: it could be easier reused, for example to process a given file containing a multipart payload, by injecting the service class and just calling its method(s) without any event coupling.

Current workaround is creating a fake request and calling `MultipartRequestListener#processRequest` using PHP's `ReflectionMethod` manually.

**Comment by goetas** [comment]
That makes sense.

Are you willing to make this change?

**Comment by Guite** [comment]
Hey @goetas 
please see the PR at #15
