### ISSUE TITLE
Throuble with v1.0.0 release

### ISSUE THREAD

**Issue by bigfoot90** [goetas/MultipartUploadBundle#8]
I'm having some throuble after the realease `1.0.0`
Until now i was forcing composer to use `"goetas/multipart-upload-bundle":       "dev-master#dabfbb162c87838f2f81f4164ac20e3cf0b57f7e"` as a workaround due to my lack of time to debug.

After upgrade to `1.0.0` Symfony is ending with error **The file could not be uploaded**.
**Request body**:
```
--delimiter
Content-Type: application/json

{"some JSON data": true}
--delimiter
Content-Disposition:form-data; name=content[images][]; filename=1px.jpg
Content-Type: image/jpeg

===binary data===
--delimiter--
```

Now I've a bit of time, and I'm trying to debug into more deeply.
I'll give you more details soon.

**Comment by goetas** [comment]
looking forward!

**Comment by goetas** [comment]
fixed in https://github.com/goetas/MultipartUploadBundle/pull/9
